### ISSUE TITLE
[@typescript-eslint/return-await] convert eslint not correctly

### ISSUE THREAD

**Issue by tjx666** [johnsoncodehk/tsslint#11]
I add some more test cases in my [fork](https://github.com/tjx666/tsslint/commit/9be3fe35aabf7f3b60a4401dbb4f5e98c97c7834#diff-b885eb087ad3d35089902a27827ccd9647511d6c497f6b06ffd82906fe70caa1), most of them works fine except the rule [@typescript-eslint/return-await](https://typescript-eslint.io/rules/return-await).

[eslint playground](https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=FAQwzgngdgxgBAMwK6wC4EsD2U7qgNxABt0ATASSgBUAnCAYRFRgAsBGACgEo4BvYOHFR0%2BAwXBoBTVEho4ACjUwBbdGEkA6KQCtJMVBwDkwiIa4BuMQF84MJqzgdJPfuLgB6d3AAimSWChjOEkADz0kVEk4UiQo1Ew4VTAwPABzOBAAdxB0VA1rYCtgUEhYRBR9LBw8QhIKajpGZhYAJm5RQRMO8VQWJUy4KEkBgFEaJRojSXHMGjNLQRs7ZsdnbsFPOABVKCGYfzAQESyc1HMJSV1K7DA4Fmmo0mwg9GUABxB9W2xhTCJEIiYTL5NxSGRyDLZXJwRQqNSaHR6AyGZaseYFIrATaKPCoW6GMCoI4YKDpcDQeCZWYAa0MABo4CiiJIQFAkG96YzyWUqTRqdFsJJDPlufBkGgqrgCMQyJRaAx7CwAMztVwZUpiioYbACgCCGoA6jTuAAuGFKJKSAA8%2BEwZAAfOtvlAwH9NIDUkZCcS0uqKXBebSLGJBCdoUMBrDLRwpK6iPgogBeR3qVBUV6STARGP%2BP4JhlsAAMxa4wbcMBubo0HqMooDNIFQ3Ri2KnREas6fSBg2GcDGEymMzmZbgS0VqxcIY8XgAsmoUqTIacQeIwbIcE99RSjXzuAtR4g8MQiBAnRWXVWa0yWWyOSOipi6%2BLrtVpXU5Y1FQAWVViLodoQuwGCM%2ByHQcJmbA9URYCcnV6foe1GMDDGmCYWkgmwECPIgTydTYdj2A4jlPMMzguK5tRdO4HkbF53k%2BVBnV%2Bf4EEBYEpzXCFSPNOF1C0S4kSMLCoGPUx70KYony1SUahlep5SaVgAFZf0ETicG4qN4X4uMEyMEx0UfDVyglHVZPfBoFWaAA2VSLnBDSoUYwxaliQxLCsIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaaRAF1ml0IEMB3agS1PSnwDM3IAacbSAAVIBPAA4oAxtAYjShFPAa5SAehLlKNekxaRE0aPmiReAXxAmgA&tsconfig=&tokens=false)

test code:

```ts
// @ts-nocheck

async function invalidInTryCatch1() {
	try {
		return Promise.reject('try');
	} catch (e) {
		// Doesn't execute due to missing await.
	}
}

async function invalidInTryCatch2() {
	try {
		throw new Error('error');
	} catch (e) {
		// Unnecessary await; rejections here don't impact control flow.
		return await Promise.reject('catch');
	}
}

// Prints 'starting async work', 'cleanup', 'async work done'.
async function invalidInTryCatch3() {
	async function doAsyncWork(): Promise<void> {
		console.log('starting async work');
		await new Promise(resolve => setTimeout(resolve, 1000));
		console.log('async work done');
	}

	try {
		throw new Error('error');
	} catch (e) {
		// Missing await.
		return doAsyncWork();
	} finally {
		console.log('cleanup');
	}
}

async function invalidInTryCatch4() {
	try {
		throw new Error('error');
	} catch (e) {
		throw new Error('error2');
	} finally {
		// Unnecessary await; rejections here don't impact control flow.
		return await Promise.reject('finally');
	}
}

async function invalidInTryCatch5() {
	return await Promise.resolve('try');
}

async function invalidInTryCatch6() {
	return await 'value';
}
```

**Comment by tjx666** [comment]
My config problem, just remove extra empty object in options array. 

change from:

```ts
'return-await': convertRule((await import('./node_modules/@typescript-eslint/eslint-plugin/dist/rules/return-await.js')).default.default, [{}], 0),
```

to:

```ts
'return-await': convertRule((await import('./node_modules/@typescript-eslint/eslint-plugin/dist/rules/return-await.js')).default.default, [], 0),
```

**Comment by johnsoncodehk** [comment]
I found that the following case is not report. Fixed by https://github.com/johnsoncodehk/tsslint/commit/8c74b397cb5f444ad88d8689c3ab4fad9fdf3a22.

```
// Prints 'starting async work', 'cleanup', 'async work done'.
async function invalidInTryCatch3() {
	async function doAsyncWork(): Promise<void> {
		console.log('starting async work');
		await new Promise(resolve => setTimeout(resolve, 1000));
		console.log('async work done');
	}

	try {
		throw new Error('error');
	} catch (e) {
		// Missing await.
		return doAsyncWork();
	} finally {
		console.log('cleanup');
	}
}
```
