### ISSUE TITLE
GET https://registry.npmjs.org/tsslint - Not found

### ISSUE THREAD

**Issue by 7flash** [johnsoncodehk/tsslint#16]
<img width="879" alt="Screenshot 2024-07-07 at 15 24 24" src="https://github.com/johnsoncodehk/tsslint/assets/4569866/2d3850aa-95dd-438f-8f67-3e2ad18ed06c">

**Comment by johnsoncodehk** [comment]
You need to install the `@tsslint/cli` package to use the `tsslint` command. Since the names of `tsslint` and `tslint` are similar, we cannot publish the package to npm under the name of `tsslint`.

**Comment by 7flash** [comment]
Yes it works after npm install -g @tsslint/cli
