### ISSUE TITLE
🚀 Feature: Compatibility layer for ESLint plugins

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [johnsoncodehk/tsslint#17]
👋 again! This and https://github.com/Quramy/typescript-eslint-language-service are two really exciting avenues of being able to run ideally much faster typed linting as a part of the TypeScript language service. Ideally we'd be able to run _all_ of a project's linting through this one - including existing ESLint plugins.

One issue that plagued TSLint back in the day was that it didn't support ESLint plugins natively. Everything had to be rewritten from ESTree to TypeScript's AST format.

Would you be interested in some kind of compatibility layer that lets folks natively use ESLint rules and plugins in TSSLint?

Vaguely guessing at an initial API design:

```js
import { defineConfig, eslintPluginCompat } from '@tsslint/config';
import example from 'eslint-plugin-example';

export default defineConfig({
	rules: {
		// ...
		eslintPluginCompat(example.recommended),
	},
});
```

It looks like `./packages/eslint` already has a [`convertRule`](https://github.com/johnsoncodehk/tsslint/blob/47f0f4bdbb68d8343c2967d46bd4b7bf9fb00e7e/packages/eslint/index.ts#L28) that does a lot of this work - so maybe this is already planned? 🙂

**Comment by JoshuaKGoldberg** [comment]
Swell! I've got a few on my personal account that exercise some edge cases:

* https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type: uses more TypeScript tooling than most
* https://github.com/JoshuaKGoldberg/eslint-plugin-package-json: made to work on `.json` files

https://github.com/eslint/eslint/issues/18093 is a good tracking issue to see plugins that support ESLint's new flat config format.

**Comment by johnsoncodehk** [comment]
I find that the `convertConfig` API is sufficient to cover current use cases, since people mainly use TSSLint to add type-aware rules, full compatibility with ESLint config doesn't make much sense to people, instead it may make TSLint config lose clarity.

If you need to completely convert a ESLint config, you can refer to https://github.com/vuejs/core/pull/12497.
