### ISSUE TITLE
Different type information when using `@typescript-eslint` with a compat layer

### ISSUE THREAD

**Issue by sheremet-va** [johnsoncodehk/tsslint#26]
I wanted to introduce this library to the Vitest monorepo: https://github.com/vitest-dev/vitest/pull/6884

But I cannot figure out the inconsistencies that I encountered and would appreciate some help:

Whatever I do in https://github.com/sheremet-va/vitest/blob/4b068e337c4782167c7aa4be59ad73ee2b96be9f/packages/spy/src/index.ts causes tsslint to think that I always return `any` even if I cast it or when the type is already known 🤔 

<img width="858" alt="Screenshot 2024-11-12 at 14 48 30" src="https://github.com/user-attachments/assets/9be753bd-5352-4c19-b8a7-728ba224acab">

**Comment by sheremet-va** [comment]
I don't know if this is an issue with the plugin itself or the language server 👀 Reoading the server didn't help, unfortunately

**Comment by johnsoncodehk** [comment]
This seems to be a bug in `@typescript-eslint/no-unsafe-return` and it can be reproduced in the ES-TSLint playground.

https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=C4TwDgpgBACgTgewMYQCYFc7QLxQBQB0RAhnAOYDOAXFMQHYgDaAugJRTYB8tDAULwDN0dJMACWCOlAh0AFvRQBlMCAA8AFWkAPYDNQVYiFBiyc87AN68oUUJCjqAShGCY6B3M9dw668BA1Oa3wAN2IAGxonFzcKdi4oMPDeAF9%2BAHp0qABZMToxAFsIqCwwRAwUXjtoAEEOHhBePCSaGvjuJN4gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolrRE%2BWNCbooiaNA7RI4MAF8QKoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

**Comment by sheremet-va** [comment]
Good to know! Thank you for looking into this ❤️

**Comment by JoshuaKGoldberg** [comment]
Nit: I don't know that we can conclude this is a bug in typescript-eslint 😅. We'd happily [take an issue](http://github.com/typescript-eslint/typescript-eslint/issues) but:

For `enhanceSpy`: `ReturnType<T>` _can_ be `any`. `Procedure`'s return type is `any`, so the constraint of `T` isn't making the return anything more narrow than `any`.

**Comment by sheremet-va** [comment]
Ah, you might be right! The default Procedure has the return type as any 🤔

**Comment by johnsoncodehk** [comment]
@JoshuaKGoldberg Yes this is most likely my misunderstanding of the no-unsafe-return rule.
