### ISSUE TITLE
Naming clash

### ISSUE THREAD

**Issue by bradzacher** [johnsoncodehk/tsslint#3]
[I posted this on twitter but I figured a GH issue was much more conducive for discussion](https://twitter.com/bradzacher/status/1742031585686511686?t=ANoO4fwRgE0LlUz_OjfepQ&s=19) 

The project seems like a nice idea - a framework for plugins is nice!

However the name is very confusing in my opinion (and based on the likes on twitter - others agree too).

- `tsslint` is just one character different to `tslint` and reads like a typo.
- It's also pretty similar to typescript-eslint which is often abbreviated to ts-eslint or `tseslint` - again `tsslint` looks like a typo.
- `tsslint` is very similar to `eslint`

Given you've just announced this project and it's in its very, very early stages - now is the best time to look to choosing a new name. Disambiguating this project and making it its own, distinct thing would be good to clarify things and help establish its own ecosystem.

**Comment by johnsoncodehk** [comment]
Now this project has been renamed to `tsl`. 🙌

**Comment by bradzacher** [comment]
Hi @johnsoncodehk was there a reason you undid this in june?

**Comment by johnsoncodehk** [comment]
I find that "tsl" is not a good project name, naming with that word makes this project almost unrecognizable.
