### ISSUE TITLE
VSCode Highlighting/Extension

### ISSUE THREAD

**Issue by LouisLP** [johnsoncodehk/tsslint#34]
After the recent fix to Vue files from #32, we've been implementing `tsslint` across multiple repositories. I'm using VSCode—based off your [guide here](https://github.com/johnsoncodehk/tsslint?tab=readme-ov-file#usage), I installed your [extension](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsslint), have the `devDependency`, and added a `tsslint.config.ts` file.

However, the following error appears on the first line of every `.ts` file (and both `.vue` and `.ts` files don't have error-highlighting):

<img width="647" alt="image" src="https://github.com/user-attachments/assets/42032e56-2bab-4044-b08d-ccf6a4a37b21" />

> `Cannot read properties of undefined (reading 'getNonBoundSourceFile')tsslint`
> `index.js(41, 61): at Object.createLinter`

Are there additional steps I'm missing?

**Comment by johnsoncodehk** [comment]
This is 1.4.5 regression introduced in #33. Can you try 1.4.6? Thanks.

**Comment by LouisLP** [comment]
Seems to work now, thanks!

<img width="481" alt="image" src="https://github.com/user-attachments/assets/94ca9c73-5c0e-4858-ad63-9370c5cd2ce8" />
