### ISSUE TITLE
Error: The package "@esbuild/darwin-arm64" could not be found, and is needed by esbuild.

### ISSUE THREAD

**Issue by kurtextrem** [johnsoncodehk/tsslint#35]
I get the "Error: The package "@esbuild/darwin-arm64" could not be found, and is needed by esbuild." error (thrown in the `tsslint.config.ts` file on the first line at `import` when trying to set up tsslint in a repo managed by Yarn.

This is my package:
```
 "dependencies": {
        "@esbuild/darwin-arm64": "0.17.19",
        "esbuild": "^0.17.19",
        "@tsslint/config": "^1.4.6",
        "@tsslint/eslint": "^1.4.6",
```

I can also clearly see it in my node_modules: 
<img width="749" alt="image" src="https://github.com/user-attachments/assets/78c06504-201b-473c-a24a-4b5dc7a63b04" />

And I also tried running `npm -g i esbuild`, which didn't resolve the issue either. Where is tsslint trying to load esbuild from? My VSC workspace is the root (e.g. where `package.json` and `tsslint.config.ts` are).

TSSLint VSC version: 1.4.6

**Comment by johnsoncodehk** [comment]
Where did you see this error? TSSLint extension does not use esbuild in your project. When the extension is started for the first time, it will [run `node_modules/esbuild/install.js`](https://github.com/johnsoncodehk/tsslint/blob/9c5bc3471bb1c737144f90a1a70470975088e7fc/packages/vscode/extension.js#L9) in the TSSLint extension directory, and then install `@esbuild/darwin-arm64` to the node_modules of TSSLint extension directory through npm install.

Maybe you have a corrupt @esbuild/darwin-arm64 installed for some reason, please try if this solves the problem.

1. Uninstall TSSLint extension.
2. Close VSCode completely. (Make sure VSCode clears uninstalled extensions)
3. Open VSCode and reinstall the TSSLint extension. The esbuild installation should now be performed again.

**Comment by kurtextrem** [comment]
Did that - didn't fix it:
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/00e481f5-f242-4200-b8d6-fa6b8c11d84a" />

**Comment by johnsoncodehk** [comment]
1. What is the size of your `~/.vscode/extensions/johnsoncodehk.vscode-tsslint-1.4.6/node_modules/esbuild/bin/esbuild` file?
2. Do these two files exist?
   - `~/.vscode/extensions/johnsoncodehk.vscode-tsslint-1.4.6/node_modules/esbuild/lib/downloaded-@esbuild-darwin-arm64-esbuild` 
   - `~/.vscode/extensions/johnsoncodehk.vscode-tsslint-1.4.6/node_modules/esbuild/bin/esbuild`

**Comment by johnsoncodehk** [comment]
I currently have no clue about this error. This is the extension installation package with built-in `@esbuild/darwin-arm64` (use VSCode "Developer: Install Extension from Location..." command to install)

[vscode-tsslint-1.4.6.vsix.zip](https://github.com/user-attachments/files/18168134/vscode-tsslint-1.4.6.vsix.zip)

If you have any clues please let me know, thanks.

**Comment by kurtextrem** [comment]
thank you!!
