### ISSUE TITLE
Provide autofix in vscode?

### ISSUE THREAD

**Issue by so1ve** [johnsoncodehk/tsslint#6]
Currently there is no autofix in vscode:

![image](https://github.com/johnsoncodehk/typescript-linter/assets/58381667/3a081a29-422e-497b-8c3d-1fed6a7b68ad)

**Comment by johnsoncodehk** [comment]
I have found this problem but can't reproduce it yet.

<img width="862" alt="image" src="https://github.com/johnsoncodehk/typescript-linter/assets/16279759/b3b89498-4a8a-457e-a91c-3f164ab3b2d8">

**Comment by johnsoncodehk** [comment]
I've been unable to reproduce the problem in 0.0.12, I'm guessing it's been resolved. But please let me know if you still face this problem.
